# Generated by Django 4.2.1 on 2023-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departements",
            fields=[
                ("DepID", models.AutoField(primary_key=True, serialize=False)),
                ("DepName", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("EmpID", models.AutoField(primary_key=True, serialize=False)),
                ("EmpName", models.CharField(max_length=30)),
                ("Empdep", models.CharField(max_length=50)),
                ("DateofJoining", models.DateField()),
                ("photoFieldName", models.CharField(max_length=100)),
            ],
        ),
    ]
